### ISSUE TITLE
Android app crashes when trying to render Compose view inside of a React Modal

### ISSUE THREAD

**Issue by erksch** [voize-gmbh/reakt-native-toolkit#80]
```jsx
<Modal>
  <MyComposeView />
</Modal>
```

leads to this crash on Android

```
FATAL EXCEPTION: main
Process: com.myrnproject, PID: 7408
java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.FrameLayout{95567eb V.E...... ......I. 0,0-0,0}
	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:352)
	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:325)
	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion.LifecycleAware$lambda$0(WindowRecomposer.android.kt:168)
	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion.$r8$lambda$PmWZXv-2LDhDmANvYhil4YZYJuQ(Unknown Source:0)
	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$$ExternalSyntheticLambda0.createRecomposer(Unknown Source:0)
	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:300)
	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)
	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)
	at androidx.compose.ui.platform.AbstractComposeView.setParentContext(ComposeView.android.kt:106)
	at androidx.compose.ui.platform.AbstractComposeView.setParentCompositionContext(ComposeView.android.kt:118)
	at com.myrnproject.shared.MySecondComposeViewRNViewManagerAndroid$ComposeViewWrapper$special$$inlined$doOnAttach$1.onViewAttachedToWindow(View.kt:433)
	at android.view.View.dispatchAttachedToWindow(View.java:20490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

If you put the view into another view it does not crash anymore but creates a RedBox with the same error:

```jsx
<Modal>
   <View>
     <MyComposeView />
   </View>
</Modal>
```
![Screenshot 2024-12-04 at 08 24 16](https://github.com/user-attachments/assets/47cde79e-ff06-4848-a3b1-59f53b3a15c9)

**Comment by erksch** [comment]
Others seem to have the same problem with Compose views inside of `<Modal>` on Android:

https://github.com/react-native-community/discussions-and-proposals/issues/446#issuecomment-1645470527
